---
- name: deployement python
  hosts: servers
  become: true
  vars:
    workspace: "ansible-tp" 
  tasks:
  - name: deployment
    copy:
      src: /var/lib/jenkins/workspace/ansible-tp
      dest: /opt
   
